name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create and Publish Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Make Distribution
        run: build/dist --all
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Package
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            *-dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
