name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create and Publish Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Make Distribution
        run: build/dist --all
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$(basename ${{ github.ref }})" ./*-dist/*
